apiVersion: v1
kind: Service
metadata:
  labels:
    service: infra-test
    version: v1
    team: infra
  name: infra-test
  namespace: utils
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4040
  selector:
    service: infra-test
    version: v1
    team: infra
  type: ClusterIP
