apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ForbidHostNamespace
metadata:
  name: forbid-host-namespace
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
