apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ForbidPrivilegedContainer
metadata:
  name: forbid-privileged-container
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
