apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: orange
  labels:
    service: frontend
    version: v1
    team: orange
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
      version: v1
      team: orange
  strategy: {}
  template:
    metadata:
      labels:
        service: frontend
        version: v1
        team: orange
    spec:
      containers:
      - image: mmingorance/demo-service
        name: frontend
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
        env:
          - name: "API_HOST"
            value: "http://backend.verde"
        ports:
          - name: http
            containerPort: 4040
            protocol: TCP
