apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-infra-namespaces-to-frontend
  namespace: orange
  labels:
    service: frontend
    version: v1
    team: orange
spec:
  podSelector:
    matchLabels:
      servicio: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          equipo: infra
