apiVersion: v1
kind: Service
metadata:
  labels:
    equipo: naranja
    servicio: frontend
    version: v1
  name: frontend
  namespace: naranja
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4040
  selector:
    equipo: naranja
    servicio: frontend
    version: v1
  type: ClusterIP
