apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: green
  labels:
    service: backend
    version: v1
    team: green
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
      version: v1
      team: green
  strategy: {}
  template:
    metadata:
      labels:
        service: backend
        version: v1
        team: green
    spec:
      containers:
      - image: mmingorance/amazing-api
        name: api
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 300Mi
        ports:
          - name: http
            containerPort: 4040
            protocol: TCP
