apiVersion: v1
kind: Service
metadata:
  labels:
    equipo: verde
    servicio: backend
    version: v1
  name: backend
  namespace: verde
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4040
  selector:
    equipo: verde
    servicio: backend
    version: v1
  type: ClusterIP
