apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend-exceed-cpu
  namespace: naranja
  labels:
    servicio: web-frontend-exceed-cpu
    version: v3
    equipo: naranja
spec:
  replicas: 1
  selector:
    matchLabels:
      servicio: web-frontend-exceed-cpu
      version: v3
      equipo: naranja
  strategy: {}
  template:
    metadata:
      labels:
        servicio: web-frontend-exceed-cpu
        version: v3
        equipo: naranja
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            cpu: "3"
            memory: "3Gi"
