apiVersion: v1
kind: Service
metadata:
  labels:
    team: orange
    service: web-frontend
    version: v1
  name: web-frontend
  namespace: orange
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    team: orange
    service: web-frontend
    version: v1
  type: LoadBalancer
