controller:
  replicaCount: 1

  nodeSelector:
    worker-role: tools

  tolerations:
    - key: "worker-role/tools"
      operator: "Exists"
      effect: "NoSchedule"

  service:
    targetPorts:
      http: 80
      https: 80
    externalIPs:
      - 192.168.178.40
      - 192.168.178.20

  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi

defaultBackend:
  enabled: true
