apiVersion: v1
kind: Service
metadata:
  labels:
    team: green
    service: web-backend
    version: v1
  name: web-backend
  namespace: green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    team: green
    service: web-backend
    version: v1
  type: ClusterIP
